### ISSUE TITLE
fxtran does not transform #ifdef contained code

### ISSUE THREAD

**Issue by QuentinRodier** [SebastienRietteMTO/PHYEX-fortran-tool#5]
produced by fxtran : 

<f:unseen>#ifdef REPRO48
IF (BUCONF%LBUDGET_TH) CALL BUDGET_STORE_ADD_PHY(D, TBUDGETS(NBUDGET_TH), 'HENU',  ZW1(:, :)*ZZ_LSFACT(:, :)*PRHODJ(:, :))
IF (BUCONF%LBUDGET_RV) CALL BUDGET_STORE_ADD_PHY(D, TBUDGETS(NBUDGET_RV), 'HENU', -ZW1(:, :)                *PRHODJ(:, :))
IF (BUCONF%LBUDGET_RI) CALL BUDGET_STORE_ADD_PHY(D, TBUDGETS(NBUDGET_RI), 'HENU',  ZW1(:, :)                *PRHODJ(:, :))
#else
</f:unseen>

**Comment by SebastienRietteMTO** [comment]
All the REPRO48 keys will be suppressed in cycle 49t1.
In the meantime, you can preprocess the code before applying your transformations.

From the fxtran help page, this could be done using the '-cpp' option of fxtran (this option can be given to pft.py this way: "--parserOption='-cpp'"). A first test shows no difference?

Counter-intuitively, you could be more interested by the -no-cpp option but the code must be rewritten in order to be parseable
